language: node_js
node_js:
- '0.10'
services:
- neo4j
deploy:
  provider: npm
  email: github@philippkueng.ch
  api_key:
    secure: E70sEXEYHqev0wmVvsJtzzoO8Dja8079ZjJ8ypy2xbwtF6FP+SMb3gNeRcEOHVg63q+jg95R6kKWwNCTlfSSt6/1UeSYC1DbIKM45UNcazQ16uy2Pr+uroZYgorc2YGHW1s0/QvmqxU7CGkGYYe/l3N+0MpxebqqJhu18VKhwGc=
  on:
    tags: true
    repo: philippkueng/node-neo4j
    branch: master
